---
kind: pipeline
name: build

steps:
- name: docker
  image: plugins/docker
  settings:
    auto_tag: true
    repo: benfairless/ci-builder
    username:
      from_secret: docker_username
    password:
      from_secret: docker_token
